### ISSUE TITLE
Move un-imported packages to "Suggests"?

### ISSUE THREAD

**Issue by trevorld** [paezha/truchet#2]
* Some of your packages in your `Imports` seem to be used only in your Examples, Tests, and Vignettes.  It might be better to move these to `Suggests` so downstream packages don't need to install them when installing `{truchet}` (such as when doing Continuous Integration testing).  When used in Examples, Tests, Vignettes you'd need to guard their usage with `requireNamespace()` blocks (or add them to the `VignetteBuilder` field in `DESCRIPTION`)...
* In particular, in the future if `{truchet}` is published to CRAN [I may try to Import/Suggest `{truchet}`](https://github.com/trevorld/gridpattern/issues/54) to make some `{grid}` graphics using ``sf::st_as_grob()`` and your `{ggplot2}` `Imports` seems to be a non-trivial dependency to download that doesn't seem to be an actual dependency for `{truchet}` but only used in its examples/vignettes...

**Comment by paezha** [comment]
Thank you for this. I am relatively new at package development and was not sure about the package used in the articles/vignettes, but I think this has been resolved. Check the DESCRIPTION file.

**Comment by trevorld** [comment]
Thanks!

If you put packages like `{ggplot2}` in `VignetteBuilder` you don't need a bunch of `requireNamespace("ggplot")` in your vignettes checking if `{ggplot2}` is available.  (You always need `{knitr}` in there).  CRAN has a test where they test your package without any `Suggested` packages installed...
